### ISSUE TITLE
Video jumps around and system crashes soon after boot

### ISSUE THREAD

**Issue by anti-matter** [ZigZagJoe/30Video-Support#2]
Hello, got my card the other day and installed it in a professionally recapped SE/30. System was fully functional before installation.

The video card is installed on top of a DiiMo Cache 50Mhz 030 accelerator. Video appears, but it is extremely jumpy side-to-side. I tried running the machine without the DiiMo, but in that case, I get horizontal bars.

![8D04DEBF-AFC8-41CD-9DB4-E5BD87E57BBB_1_105_c](https://github.com/user-attachments/assets/648f9996-0289-4252-bb04-e2f33caf8fca)

Here's a video with it installed on top of the DiiMo, note that the system crashed before the monitors control panel opened:

https://github.com/user-attachments/assets/ed261ce8-00a2-4f3f-84ee-a918726c1f96

Here it is during boot. You can see that the video stops shaking as soon as the system freezes. Not sure if that means anything.

https://github.com/user-attachments/assets/7b62b4db-50e3-464f-b818-ea539e2105e1

I tried reseating all connectors. I tried _jiggling_ the harness, but that doesn't appear to make the display unstable - it just does it on it's own.

Any further troubleshooting steps?

Thanks.

**Comment by ZigZagJoe** [comment]
Hey! Sorry to hear that you're having issues!

It's not a loose connection; the 30Video card is having trouble maintaining a lock to the system clock and this is how it results. The "jiggling" display is a symptom of a weak/overloaded system clock signal. The Diimo is only buffering one of the clock signals, and the 30Video card is pulling the unbuffered system clock. This **should** be fine, but it appears for some reason in your case it is not. 

There's a few options we might take to resolve this, but first I'd like to better understand your setup. Can you give me a little details on what else you have installed? Also, what power supply do you have? Do you know the voltage you're seeing on your 5V line? 

Just so I'm clear - you get horizontal bars with just the 30Video card installed and not the Diimo? Or is that with no cards installed at all/no grayscale harness? The 30Video card should certainly be functional by itself.

Thanks!

**Comment by anti-matter** [comment]
Thanks for the quick response!

> Can you give me a little details on what else you have installed? Also, what power supply do you have? Do you know the voltage you're seeing on your 5V line?

- The only things I can think of to tell you is that it has 64mb of RAM and a BlueSCSI w/ WiFi. Other than the BlueSCSI and the DiiMo, it's stock.
- Power supply is the non-Sony one. But, it was rebuilt professionally.
- I don't have a volt meter here, but I would assume the 5V line is working as it was just tested when it was rebuilt earlier this year.

> Just so I'm clear - you get horizontal bars with just the 30Video card installed and not the Diimo? Or is that with no cards installed at all/no grayscale harness? The 30Video card should certainly be functional by itself.

- The horizontal lines appear with ONLY the 30Video card installed. Don't get a power-on chime either.
- The machine functions perfectly fine with and without the DiiMo using the stock video.
- Lastly, with NO cards installed, but with the 30Video neckboard and harness, the machine does chime at power-on, but obviously, there's no video.

**Comment by ZigZagJoe** [comment]
Hmmmmm.... That's extremely odd, to say the least. It should not be causing horizontal lines (symptom of the CPU not running or encountering an early issue). I don't expect it to make a difference, but can you try with the Diimo on top of the 30Video card?

With regards to voltage, It's not so much a lack of function as low voltage on the 5v that can be an issue, though if the diimo was happy before it ought to be happy after as the grayscale harness uses heavier gauge power wires to lesson voltage drop. Do you know if the diimo was installed when person who rebuilt the PSU adjusted it?

**Comment by anti-matter** [comment]
No, the DiiMo was not installed when the person who rebuilt it adjusted the PSU. However, I do lots of work with this guy and he knows I planned on running an accelerator in it. In fact, he also fixed the accelerator card (had bad caps and a broken pin on one of the chips). I can go grab a meter tomorrow and do a check on the 5V line though, you never know. How exactly should I check that?

I'll also try the DiiMo on top of the 30Video card.

**Comment by ZigZagJoe** [comment]
Sounds like a plan. Here are two places you can check: At the floppy port, and if you have the 30video on top of the diimo, it has voltage check points also which may be easier to access.

![20240919_080400](https://github.com/user-attachments/assets/f6ed4096-9a46-4927-81a2-9f5ae8e61316)
![floppy-connector-pinout](https://github.com/user-attachments/assets/31427f53-eaf8-41c0-89fb-887bddac8487)

**Comment by anti-matter** [comment]
Update: I swapped the order of the boards (DiiMo on top of 30Video) and now the system works perfectly!

**Comment by ZigZagJoe** [comment]
I'm glad to hear that! Give it a full run-in and of course, let me know if anything comes up.

I'd still recommend checking your 5V just for peace of mind: as it's always good to know where that lies as it you can get some real gremlins when it's a bit low.

**Comment by anti-matter** [comment]
Will do. It's been running for over an hour now, no issues.

Do you still have units for sale? Would like another one. :) You can email me at mconrad@me.com

**Comment by ZigZagJoe** [comment]
Fantastic news. It ought to be good, then. 
I'm planning to keep these in continuous production, so I'll send you an email!
